### ISSUE TITLE
Pesquisar sobre os temas do projeto

### ISSUE THREAD

**Issue by modestoo** [deeplearningunb/music-fusion#4]
**Tasks**

- [x] RNN (Recurrent neural network)
- [x] NLP (Natural Language Processing)
- [x] API para consumir letras de músicas (Português)

**Comment by Ronyell** [comment]
As explicações a respeito de NLP e RNN estão presentes no README.md. E a api encontrada para obter as músicas do dataset foi a do vagalume. https://api.vagalume.com.br/
