### ISSUE TITLE
Realizar treinamento da rede

### ISSUE THREAD

**Issue by modestoo** [deeplearningunb/music-fusion#7]
**Description**
Realizar treinamento da rede 

**Tasks**
- [x] Realizar treinamento inicial da rede
- [x] Ajustar os hiperparâmetros da rede
- [x] Realizar re-treinamento da rede
